name: JS

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    name: Lint JS

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run ESLint
        run: npm run lint
